version: '2.4'
services:
  db:
    image: mysql
    container_name: mysql3
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    mem_limit: 512m
    volumes:
      - devdojo_data:/var/lib/mysql

volumes:
  devdojo_data:

